meta_product_name: "Outflix"
meta_title: "Outflix | Expiring Content Tracker"
meta_description: "Never miss out on the chance to watch a Netflix title before it leaves the platform ever again."
meta_image: "facebook-card.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
